<?php

namespace app\common\Entity;

use app\common\model\BaseModel;
use app\common\Utils\Request;
use think\model\concern\SoftDelete;

/**
 * This is the model class for table "ecs_user_card_info".
 *
 * @property int $id
 * @property  int $is_delete
 */
class MemberCardInfo extends BaseModel
{
    use SoftDelete;


    protected $table = 'ecs_member_card_info';

    protected $deleteTime = 'is_delete';
    protected $defaultSoftDelete = 0;


    public static function getPageList(array $requestData = [])
    {


        $page = Request::getPage();
        $pageSize = Request::getLimit();

        $ar = self::field('id,type,alipay_account,bank_name,bank_number')
            ->where('user_id', $requestData['user_id']);


        $result['count'] = $ar->count('id');
        $result['pagecount'] = ceil(($result['count'] / $pageSize));
        $result['list'] = $ar->page($page, $pageSize)->select();

        return $result;
    }


    public static function getInfoById(int $id)
    {
        return static
            ::where('id', $id)
            ->find();
    }

    public static function getInfoByIdWithUserId(int $id, int $user_id)
    {
        return static
            ::where('id', $id)
            ->where('user_id', $user_id)->find();
    }


    public static function create($data = [], $field = null, $replace = false)
    {
        $field = ['user_id', 'type', 'alipay_account', 'bank_name', 'bank_number'];
        return parent::create($data, $field, $replace); // TODO: Change the autogenerated stub
    }

}