<?php

namespace app\common\Entity;


use app\common\model\BaseModel;


/**
 * This is the model class for table "ecs_user_card_info".
 *
 * @property int $id
 * @property  string $name
 * @property int $level
 * @property float $discount
 * @property float $capping_price
 * @property float $recommend_award
 */
class VipSetting extends BaseModel
{
    protected $table = 'ecs_vip_setting';


    public static function getInfoByLevel(int $level, string $fields = '')
    {
        return static::getInfo('level', $level, $fields);
    }

    /* @return VipSetting */
    public static function getMaxLevelInfoByVsIds(array $sv_id)
    {
        return static::whereIn('id', $sv_id)->field('id,discount')->order('level desc')->find();
    }

    /* @return VipSetting */
    public static function getInfoById(int $id, string $fields = '')
    {
        return static::getInfo('id', $id, $fields);
    }


    public static function create($data = [], $field = null, $replace = false)
    {
        $field = ['name', 'level', 'first_reback_rate', 'second_reback_rate', 'third_reback_rate', 'discount', 'capping_rate', 'capping_price', 'achievement_award','recommend_award'];
        return parent::create($data, $field, $replace); // TODO: Change the autogenerated stub
    }

    public static function getCollectionByIds(array $vs_ids)
    {
        return static::field('id,name')
            ->whereIn('id', $vs_ids)
            ->select()->toArray();
    }
}